// V0180: Optional RSS music sources. Configure RSS_MUSIC_FEEDS as a comma-separated
// list of HTTPS feed URLs whose publishers permit indexing and direct audio links.
// Only explicit audio enclosures are returned; no scraping of download pages.
const decode = s => String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const field=(xml,tag)=>decode((xml.match(new RegExp('<(?:[\\w-]+:)?'+tag+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:[\\w-]+:)?'+tag+'>','i'))||[])[1]||'').trim();
const norm=s=>String(s||'').toLowerCase().replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const matches=(q,title,artist)=>{const query=norm(q),name=norm(title+' '+artist),words=query.split(/\s+/).filter(Boolean);if(!words.length)return false;if(/بندری|جنوبی/.test(query)&&!/بندری|بندر|جنوبی/.test(name))return false;if(/شاد/.test(query)&&!/شاد|رقص|جشن|عروسی|مبارک/.test(name))return false;return words.every(w=>name.includes(w))||(/بندری|جنوبی/.test(query)&&/شاد/.test(query)&&/بندری|بندر|جنوبی/.test(name)&&/شاد|رقص|جشن|عروسی/.test(name));};
const safeUrl=(raw)=>{try{const u=new URL(decode(raw));return u.protocol==='https:'?u.href:''}catch{return ''}};
async function readFeed(raw){const url=safeUrl(raw);if(!url)return [];const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),7000);try{const r=await fetch(url,{signal:ctrl.signal,headers:{Accept:'application/rss+xml, application/xml, text/xml'}});if(!r.ok)return [];const xml=await r.text();if(xml.length>1500000)return [];const items=xml.match(/<item\b[\s\S]*?<\/item>/gi)||[];return items.slice(0,120).map(item=>{const title=field(item,'title'),artist=field(item,'artist'),page=safeUrl(field(item,'link'));const enclosures=[...item.matchAll(/<enclosure\b([^>]*?)\/?\s*>/gi)];let mp3='';for(const e of enclosures){const a=e[1];const src=(a.match(/\burl\s*=\s*["']([^"']+)["']/i)||[])[1];const type=(a.match(/\btype\s*=\s*["']([^"']+)["']/i)||[])[1]||'';if(/audio\/|\.mp3(?:\?|$)/i.test(type+' '+src)){mp3=safeUrl(src);if(mp3)break;}}return {title,artist,page,mp3}}).filter(x=>x.title&&x.mp3)}catch{return []}finally{clearTimeout(timer)}}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=180, stale-while-revalidate=300');if(req.method!=='GET')return res.status(405).json({error:'روش درخواست مجاز نیست'});const q=String(req.query.q||'').trim().slice(0,100);if(!q)return res.status(400).json({error:'عبارت جستجو خالی است'});const feeds=String(process.env.RSS_MUSIC_FEEDS||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,8);if(!feeds.length)return res.status(200).json({data:[],total:0,hasNext:false,configured:false,message:'هنوز فید RSS مجاز در تنظیمات سرور ثبت نشده است.'});const results=await Promise.all(feeds.map(readFeed));const seen=new Set(),data=[];for(let i=0;i<results.length;i++)for(const item of results[i]){if(!matches(q,item.title,item.artist))continue;const key=norm(item.title+' '+item.artist);if(seen.has(key))continue;seen.add(key);data.push({id:'rss-'+data.length,name:item.title,artist:item.artist,source:'RSS',source_url:item.page,download_allowed:true,files:{mp3:item.mp3,download:item.mp3},duration:0,is_premium:false});}return res.status(200).json({data:data.slice(0,100),total:data.length,hasNext:false,configured:true});}
